### ISSUE TITLE
Source: Social distancing

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-safegraph#1]
# Status
- [ ] Load to database
- [ ] Schema finalized
- [ ] Deliverables finalized

# Description

# Output schema

### Table name: safegraph_weekly_county_trips #21 
Output the number of trips between counties for all counties in the region.  If it's easiest to filter by state do NY, NJ, PA, CT, RI, MA, VT, NH.

| Input field name | Data Type   | Output field name | Output example | Description |
|------------------|-------------|-------------------|----------------|----------------|
| date              | `IYYY-IW`    | year_week               | 2020-30    | Week of the year and the year |
|-              | `text`    | origin               | 36061   | Origin county (roll up block groups to county level) |
|-         | `text`    | destination               | 36085     | Destination county (roll up block groups to county level) |
| -              | `numeric`    | weekday_trips               | 100    | Number of trips made from origin county to destination county on the weekdays |
| -              | `numeric`    | weekend_trips               | 50    | Number of trips made from origin county to destination county on the weekend |
| -              | `numeric`    | all_trips               | 150    | Total number of trips made from origin county to destination county for the given week |

### Table name: safegraph_weekly_state_trips #22 
Output the number of trips between NYC and each state.

| Input field name | Data Type   | Output field name | Output example | Description |
|------------------|-------------|-------------------|----------------|----------------|
| date              | `IYYY-IW`    | year_week               | 2020-30    | The week of the year and the year |
| -              | `text`    | state             | 06    | Two character FIPS code of the state that is either an origin or destination of a trip to or from NYC |
|-              | `numeric`    | to_nyc               | 100    | The number of trips coming into NYC from the given state |
|-         | `numeric`    | from_nyc              | 500     | The number of trips going out of NYC to the given state |
| -              | `numeric`    | net_nyc             | -400    | The net number of trips between NYC and the given state for the week |

# Deliverables
- safegraph_weekly_county_trips.csv
safegraph_weekly_county_trips_weekends.csv
- safegraph_weekly_state_trips.csv
- Shapefile of state boundaries, where the NY boundary excludes NYC, that can get joined with safegraph_trips_by_state for the sake of mapping
- Shapefile of county boundaries in NY, NJ, PA, CT, RI, MA, VT, NH that can get joined with safegraph_trips_by_county for the sake of mapping

# Pipeline
> this is for source specific processing requirements, tag all sub issues related with this data source for easier status tracking. e.g. 
> - [ ] data ingestion #{ issue number here }
> - [ ] data transformation #{ issue number here }
> - [ ] data export #{ issue number here }

**Comment by AmandaDoyle** [comment]
Potential enhancements: Break into weekend vs weekday.
Break the nested json to columns and aggregate origin to borough and destination to counties within the region and outside of the US? 
[03-wk1_bigtable.xlsx](https://github.com/NYCPlanning/db-safegraph/files/5162986/03-wk1_bigtable.xlsx)

**Comment by mgraber** [comment]
Documentation moved to [wiki](https://github.com/NYCPlanning/db-safegraph/wiki)
