### ISSUE TITLE
Source: Point of interest

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-safegraph#13]
# Status
- [ ] Load to database
- [ ] Schema finalized
- [ ] Deliverables finalized

# Description

# Output schema

## Table name: safegraph_daily_nyc_poivisits #20 

Daily data with visits for points of interests only within NYC.

| Input field name | Data Type   | Output field name | Output example | Description |
|------------------|-------------|-------------------|----------------|----------------|
| date_range_start / date_range_end  | `YYYY-MM-DD`    | date             | 2020-08-12    | Day of the week |
| location_name              | `text`    | poi               | Sears   | Name of the point of interest |
| address              | `text`    | address               | 120 Broadway   | Address of POI from Safegraph|
| poi_cbg             | `text`    | poi_cbg               | 360470792003 | Census block group of POI |
| naics_code           | `text`    |  naics_code             |  611110  | NAICS 6-digit sector code |
| visits_by_day       | `int`    | visits             | 100     | Number of visits made to that point of interest on that day |
| latitude     | `double`    | latitude           | -73.89938034     | Latitude of the POI |
| longitude     | `double`    | longitude           | 40.89938034     | Longitude of the POI |

## Table name: safegraph_daily_borough_poivisits_by_sector #23 

Aggregate daily data with visits for points of interests within NYC by NAICS code.

| Input field name | Data Type   | Output field name | Output example | Description |
|------------------|-------------|-------------------|----------------|----------------|
| poi_cbg | `text` | borough | Manhattan | Borough for the aggregate data |
| poi_cbg | `int` | borocode | 1 | Borough for the aggregate data |
| poi_cbg | `int` | fips_county | 36061 | Borough for the aggregate data |
| date_range_start / date_range_end  | `YYYY-MM-DD`    | date             | 2020-08-12    | Day of the week |
| naics_code           | `text`    |  naics_code             |  611110  | NAICS 6-digit sector code |
| visits_by_day       | `int`    | total_visits             | 100     | Number of visits made to POIs in that sector |

## Table name: safegraph_weekly_nyc_poivisits #18 

Weekly data with visits broken out for weekday and weekend for points of interests only within NYC.

| Input field name | Data Type   | Output field name | Output example | Description |
|------------------|-------------|-------------------|----------------|----------------|
| date_range_start / date_range_end  | `IYYY-IW`    | year_week               | 2020-30    | Week of the year and the year |
| location_name              | `text`    | poi               | Sears   | Name of the point of interest |
| address              | `text`    | address               | 120 Broadway   | Address of POI from Safegraph|
| poi_cbg             | `text`    | poi_cbg               | 360470792003 | Census block group of POI |
| naics_code           | `text`    |  naics_code             |  611110  | NAICS 6-digit sector code |
| visits_by_day       | `int`    | visits _weekday              | 100     | Number of visits made to that point of interest on the weekdays of given week |
| visits_by_day         | `int`    | visits_weekend               | 50     | Number of visits made to that point of interest on the weekends of given week|
| visits_by_day     | `int`    | visits_total           | 150     | Number of visits made to that point of interest during the given week |
| latitude     | `double`    | latitude           | -73.89938034     | Latitude of the POI |
| longitude     | `double`    | longitude           | 40.89938034     | Longitude of the POI |

# Deliverables
safegraph_weekly_nyc_poivisits.csv
safegraph_nyc_pois.zip (point shapefile of just NYC POIs with fields poi, address, poi_cbg, naics_code, latitude, longitude).

# Pipeline
> this is for source specific processing requirements, tag all sub issues related with this data source for easier status tracking. e.g. 
> - [ ] data ingestion #{ issue number here }
> - [ ] data transformation #{ issue number here }
> - [ ] data export #{ issue number here }

**Comment by mgraber** [comment]
Documentation moved to [wiki](https://github.com/NYCPlanning/db-safegraph/wiki)
